FROM node:20-alpine

WORKDIR /app

COPY ../../package*.json ./
COPY ../../apps/frontend/package*.json ./apps/frontend/
COPY ../../apps/frontend ./apps/frontend

RUN npm install
WORKDIR /app/apps/frontend

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
