FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY apps/backend/package*.json ./apps/backend/
COPY tsconfig*.json ./
COPY apps/backend ./apps/backend

RUN npm install
WORKDIR /app/apps/backend

CMD ["npm", "run", "start:dev"]
